# Generated by Django 5.2.6 on 2025-10-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computertype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
