# Generated by Django 5.2.6 on 2025-09-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetComputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('graphics_card', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
    ]
